migrations/1736262780704_create-default-tables.ts
src/db/index.ts
src/db/types.ts

kysely를 사용해 데이터베이스 스키마 타입 정의와 마이그래이션 파일을 생성하였습니다.
>

Feat: 데이터베이스 스키마 타입 정의 & 마이그래이션 파일 생성

---

migrations/1736415967845_create-notification-and-last-read-message.ts
migrations/1736415967845_create-notifications-and-last-read-messages.ts
src/db/index.ts
src/db/types.ts

last_read_message와 notification 테이블을 생성하였습니다.
notification 테이블의 is_checked 컬럼을 위해 TINYINT 자리수가 1일 경우 true/false 로 형변환 합니다.
>

Feat: last_read_message, notificaiton 테이블 생성

---

package.json
pnpm-lock.yaml

Chore: jsonwebtoken 추가

---

.gitignore
package.json
pnpm-lock.yaml
src/config/swagger.ts

tsc + tsc-alias + nodemon 조합을 tsx로 변경하였습니다.
디펜던시 수가 줄어든 것도 있고 속도도 소폭 상승한 것 같습니다.. 흠흠
해당 PR 적용 후 `node_modules` 삭제 후 `pnpm install` 다시 진행하는게 나을 것 같습니다
>

Feat: tsx 마이그레이션

---

package.json
pnpm-lock.yaml
src/app.ts
src/controllers/stores.controller.ts
src/interfaces/http-exception.interface.ts
src/middlewares/error.middleware.ts

오류 처리 미들웨어를 구현하였습니다.
```ts
import HttpException from "@/interfaces/http-exception.interface";
```
임포트 후
```ts
throw new HttpException(404, "존재하지 않는 가게입니다.");
```
형식으로 사용할 수 있습니다.
해당 방식으로 HTTP 요청을 해보면 status code는 `404`, body는 `{ message: "존재하지 않는 가게입니다." }` 로 반환됩니다.
>

Feat: 오류 처리 미들웨어 구현

---

src/controllers/stores.controller.ts
src/middlewares/auth.middleware.ts
src/routes/stores.route.ts
src/services/stores.service.ts

여러 브랜치로 나누기엔 하나씩밖에 없어 한 브랜치로 묶었습니다.
- stores endpoint의 index url을 수정하였습니다.
- stores endpoint의 중복되는 authMiddleware를 분리하였습니다.
- Auth 미들웨어에 HttpException을 사용하였습니다.
- Stores 컨트롤러에 import 별칭을 사용하였습니다.
>

Fix: 자잘한 변경점 수정

---

migrations/1736691828614_change-schedules-time-type.ts
src/app.ts
src/config/swagger.ts
src/controllers/schedules.controller.ts
src/controllers/stores.controller.ts
src/db/types.ts
src/interfaces/schedules.interface.ts
src/routes/schedules.route.ts
src/routes/stores.route.ts
src/services/schedules.service.ts

- 일정 엔드포인트를 구현하였습니다.
- GET /schedules
- POST /schedules
- GET /schedules/:storeId
- PUT /schedules/:scheduleId
- DELETE /schedules/:scheduleId
- 데이터베이스 마이그레이션 파일을 생성하였습니다.
- 뭔가를 자잘하게 많이 한 것 같은데 기억이 나지 않습니다
권한 체크가 정상적으로 작동하는지
~~jwt에 저장된 role을 먼저 비교했어야 하는지도 고민되기도 하고 그렇습니다~~ < 적용되었습니다.
>

Feat: 일정 엔드포인트 구현

---

package.json
pnpm-lock.yaml
src/config/swagger.ts
src/controllers/stores.controller.ts
src/middlewares/validate.middleware.ts
src/routes/schedules.route.ts
src/routes/stores.route.ts
src/schemas/common.schema.ts
src/schemas/schedules.schema.ts
src/schemas/stores.schema.ts
src/utils/ko-zod.ts

Zod를 사용하여 validation을 하도록 했습니다.
```ts
import { z } from "@/utils/ko-zod";
export const createStoreSchema = z.object({
body: z.object({
title: z.string().min(1).max(255),
location: z.string().min(1).max(255),
contact: z.string().regex(/^[01]\d{7,11}$/, "숫자만 포함한 전화번호 형식이어야 합니다."),
password: z.string().min(1).max(255),
}),
});
```
와 같이 만들어 라우터에 middleware 형식으로 적용하면 됩니다.
```ts
router.post(
"",
validate(createStoreSchema),
createStore,
);
```
>

Feat: Zod Validation 적용

---

migrations/1736752787881_reduce-schedule-id-column-length.ts
src/config/swagger.ts
src/schemas/common.schema.ts
src/services/schedules.service.ts

schedule 길이가 길다고 판단하여 16자 -> 12자로 수정하였습니다.
>

Feat: schedule id 컬럼 길이 12로 수정

---

package.json
pnpm-lock.yaml
src/app.ts
src/config/swagger.ts
src/controllers/auth.controller.ts
src/interfaces/auth.interface.ts
src/provider/emailProvider.ts
src/routes/auth.route.ts
src/schemas/auth.schema.ts
src/schemas/stores.schema.ts
src/services/auth.service.ts

- 회원가입 및 로그인 구현
- 비밀번호 확인 및 변경 구현
- 회원가입시 이메일을 통한 본인 인증 구현
>

Feat : /auth 기능구현

---

src/config/swagger.ts

title, description, servers 를 수정하였습니다.
포트 번호가 변경되면 swagger에 반영되게 처리하였습니다.
>

Feat: 스웨거 일부 수정

---

migrations/1736831817598_add-business-hours.ts
src/config/swagger.ts
src/db/types.ts
src/interfaces/stores.interface.ts
src/schemas/stores.schema.ts
src/services/stores.service.ts

프론트 요청으로 가게에 영업시간 (`openTime`, `closeTime`) 을 추가하였습니다.
>

Feat: 가게 영업시간 추가

---

src/config/swagger.ts
src/controllers/stores.controller.ts
src/interfaces/stores.interface.ts
src/routes/stores.route.ts
src/services/stores.service.ts

가게 정보를 수정하는 엔드포인트를 구현하였습니다.
- PUT /stores/:storeId
>

Feat: 가게 정보 수정 구현

---

package.json
src/app.ts
src/config/swagger.ts
src/controllers/auth.controller.ts
src/controllers/chat.contoller.ts
src/controllers/socket.controller.ts
src/interfaces/socket.interface.ts
src/routes/chat.route.ts
src/services/chat.service.ts

- 소켓 기본 세팅 및 채팅방 구분 해서 메시지 전송/저장 까지 구현했습니다.
- 프론트와 협의해서 라스트 메시지 저장 방법 추가해야할 것  같습니다.
>

Feat : 소켓 설정 및 채팅방 별 메시지 전송/저장 구현

---

package.json
src/controllers/chat.contoller.ts
src/services/chat.service.ts

- 채팅방 상세 조회시 마지막 읽은 메시지 업데이트 해주는 로직 추가했습니다.
>

Fix : 채팅방 조회할 때 lastMessage 셋팅해주는 로직 추가

---

migrations/1736944033803_contact-not-null.ts
package.json
src/app.ts
src/config/swagger.ts
src/controllers/chat.contoller.ts
src/controllers/socket.controller.ts
src/interfaces/socket.interface.ts
src/routes/chat.route.ts
src/services/chat.service.ts

데이터베이스 마이그레이션이 필요합니다. (contact 필드 notNull 적용)
디펜던시 정리와 코드 포매팅을 진행하였습니다.
>

Feat: 여러가지 변경점

---

migrations/1736992679588_create-chat_notification.ts
src/db/types.ts

- lastReadMessage 수정 및 chatNotification 테이블 생성했습니다.
>

Fix : lastReadMessage 수정 및 chatNotification 테이블 생성

---

.github/workflows/code-quality.yml

코드 품질 유지를 위해 Github Actions 워크플로우를 추가하였습니다.
이제 PR 마다 타입 체크, ESLint, Prettier 검사를 실행합니다.
>

Feat: 코드 품질 체크 워크플로우 생성

---

.github/workflows/code-quality.yml
migrations/1736992679588_create-chat_notification.ts
src/db/types.ts

워크플로우 테스트 겸 코드 포매팅 작업을 진행합니다.
>

Style: 워크플로우 테스트 겸 코드 포매팅

---

.github/workflows/update-cache.yml

main 브랜치에 push가 일어날 시 캐싱을 진행하여 PR에서도 해당 캐시를 사용할 수 있게 하기 위한 워크플로우 입니다.
>

Feat: 메인 브랜치 pnpm 캐싱

---

src/db/index.ts

- 프론트에서 시간 오류 난다고 해서 db 설정 한 줄 추가했습니다.
>

Fix : db datestring 추가

---

src/controllers/auth.controller.ts
src/routes/auth.route.ts

- auth에 비밀번호 체크 엔드포인트가 잘못 돼 있어서 수정했습니다.
>

Fix : auth 라우터 비밀번호 체크 엔드포인트 수정

---

src/controllers/auth.controller.ts

Fix : 비밀번호 확인 오류 해결

---

src/controllers/stores.controller.ts
src/routes/stores.route.ts

가게 생성 시 사장님 계정만 생성할 수 있게 수정하였습니다.
>

Feat: 사장님 권한 필터링

---

src/controllers/auth.controller.ts
src/services/auth.service.ts

로그인 시 request 바디에 role 값 추가해 줬습니다.
>

Fix : 로그인 시 바디에 role 추가.

---

src/config/swagger.ts
src/controllers/notifications.controller.ts
src/monitors/notifications.monitor.ts
src/routes/notifications.route.ts
src/services/chat.service.ts

Fix : 채팅 sse 알림 변경

---

src/config/swagger.ts
src/controllers/schedules.controller.ts
src/interfaces/schedules.interface.ts
src/routes/schedules.route.ts
src/schemas/schedules.schema.ts
src/services/schedules.service.ts

일정 생성 엔드포인트를 `POST /schedules` 에서 `POST /schedules/{storeId}` 로 변경하였습니다.
>

Fix: 일정 생성 엔드포인트 수정

---

src/services/auth.service.ts

Fix : 개인정보 조회시 id 값 추가.

---

src/controllers/stores.controller.ts

가게 생성 시 가게의 타입이 오지 않는 경우 혹은 기타 인 경우에는 페이지 생성하지 않도록 했습니다.
>

Fix : 카테고리에 따른 기본 교육페이지 생성시 예외처리

---

src/app.ts

json body에서 길이 limit을 50mb로 상향시켰습니다.
>

Feat: json limit 50mb로 상향

---

src/utils/session-manager.ts

SSE 다중 세션용 패치를 진행하였습니다.
`sessions` 의 타입이 `Map<string, Session>` 에서 `Map<string, Session[]>` 으로 교체되었습니다.
>

Feat: SSE 다중 세션 허용

---

.dockerignore
.github/workflows/docker-build.yml
Dockerfile
docker-compose.yml
src/config/swagger.ts

도커로 서비스를 올리기 위해 docker image를 배포합니다.
`ghcr.io/albaschool/backend` 이미지로 배포가 됩니다.
>

Feat: 도커 이미지 배포

---

Dockerfile
src/config/swagger.ts
src/services/chat.service.ts
src/services/stores.service.ts

채팅 상세와 가게 직원 목록에 프로필 필드를 추가하였습니다.
>

Feat: 유저 프로필 추가

---

src/controllers/chat.controller.ts
src/services/chat.service.ts
src/services/schedules.service.ts

- 페이징 기능 추가했습니다.
- 스케줄 서비스 로직에 테이블 이름 변경했습니다.
>

Feat : 채팅방 페이징 기능 추가.

---

src/services/chat.service.ts

페이징 시작 시점 명확히 하도록 쿼리문 수정했습니다.
>

Fix : 페이징 시 시작  메시지 기준으로 페이징 쿼리문 수정

---

src/controllers/stores.controller.ts

가게에서 직원 삭제 시 일정을 삭제하는데 그 직원의 일정이 존재하지 않을 때 오류가 발생하던 것을 제거하였습니다.
>

Fix: 직원 삭제 시 일정 없을 때 오류 발생 제거

---

src/config/swagger.ts
src/controllers/auth.controller.ts
src/routes/auth.route.ts
src/services/auth.service.ts

Feat : 회원정보 수정 기능 추가.

---

src/config/swagger.ts
src/controllers/auth.controller.ts
src/controllers/socket.controller.ts
src/interfaces/socket.interface.ts
src/routes/auth.route.ts
src/services/auth.service.ts
src/services/chat.service.ts

소켓으로 메시지 넘겨줄 때 message new Date() 해서 넘기는 것으로 수정했습니다.
>

Fix : 소켓으로 메시지 넘겨줄 때 message new Date() 해서 넘기는 것으로 수정

---

src/controllers/stores-edu.controller.ts
src/services/stores-edu.service.ts

교육페이지 추가 생성 시 알림 등록했습니다. 사장은 알림이 갈 필요 없을 거 같아서 사장을 제외 하고 알림 넣었습니다.
>

Fix : 교육 페이지 추가 생성 시 알림 등록
